version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
      runtime:
        dependency-type: production
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - ci
