#!/usr/bin/env bash
# release-monitor.sh — npm + GitHub stats one-shot dump
#
# Usage:
#   scripts/release-monitor.sh                  # full report to stdout
#   scripts/release-monitor.sh --since 7d       # filter ranges (default: 7d)
#   scripts/release-monitor.sh --markdown       # GitHub-friendly markdown output
#
# Requires: npm, gh, jq, curl. No external services.

set -euo pipefail

PKG="${PKG:-think-prompt}"
REPO="${REPO:-must-goldenrod/think-prompt}"
SINCE_DAYS=7
MARKDOWN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE_DAYS="${2%d}"; shift 2 ;;
    --markdown) MARKDOWN=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

since_iso=$(date -u -v-"${SINCE_DAYS}"d +"%Y-%m-%d" 2>/dev/null || date -u -d "${SINCE_DAYS} days ago" +"%Y-%m-%d")
today=$(date -u +"%Y-%m-%d")

H() {
  if [[ "$MARKDOWN" -eq 1 ]]; then echo ""; echo "## $1"; echo ""; else echo ""; echo "═══ $1 ═══"; fi
}
KV() {
  if [[ "$MARKDOWN" -eq 1 ]]; then echo "- **$1:** $2"; else printf "  %-22s %s\n" "$1" "$2"; fi
}

echo "📦 think-prompt release monitor"
echo "Window: $since_iso → $today  (last ${SINCE_DAYS} days)"

H "npm registry"
latest=$(npm view "$PKG" version 2>/dev/null || echo "unknown")
KV "package" "$PKG"
KV "latest version" "$latest"
KV "homepage" "https://www.npmjs.com/package/$PKG"
published=$(npm view "$PKG" time --json 2>/dev/null | jq -r ".[\"$latest\"]" 2>/dev/null || echo "?")
KV "published" "$published"

H "npm download stats"
# api.npmjs.org point endpoint covers fixed periods; for last week:
weekly=$(curl -fsS "https://api.npmjs.org/downloads/point/last-week/$PKG" 2>/dev/null | jq -r '.downloads // "?"' 2>/dev/null || echo "?")
monthly=$(curl -fsS "https://api.npmjs.org/downloads/point/last-month/$PKG" 2>/dev/null | jq -r '.downloads // "?"' 2>/dev/null || echo "?")
KV "last 7 days" "$weekly"
KV "last 30 days" "$monthly"

# Daily breakdown (last 14 days for trend)
range_start=$(date -u -v-13d +"%Y-%m-%d" 2>/dev/null || date -u -d "13 days ago" +"%Y-%m-%d")
range_url="https://api.npmjs.org/downloads/range/${range_start}:${today}/${PKG}"
echo ""
if [[ "$MARKDOWN" -eq 1 ]]; then echo "**Daily downloads (last 14 days):**"; echo ""; echo '```'; fi
curl -fsS "$range_url" 2>/dev/null | jq -r '.downloads[] | "\(.day)  \(.downloads)"' 2>/dev/null | tail -14 || echo "  (no data yet)"
if [[ "$MARKDOWN" -eq 1 ]]; then echo '```'; fi

H "GitHub repo activity (last ${SINCE_DAYS} days)"
new_issues=$(gh issue list --repo "$REPO" --state all --search "created:>=$since_iso" --json number --jq 'length' 2>/dev/null || echo "?")
new_bugs=$(gh issue list --repo "$REPO" --state all --label bug --search "created:>=$since_iso" --json number --jq 'length' 2>/dev/null || echo "?")
open_total=$(gh issue list --repo "$REPO" --state open --json number --jq 'length' 2>/dev/null || echo "?")
new_prs=$(gh pr list --repo "$REPO" --state all --search "created:>=$since_iso" --json number --jq 'length' 2>/dev/null || echo "?")
stars=$(gh api "repos/$REPO" --jq '.stargazers_count' 2>/dev/null || echo "?")
KV "new issues" "$new_issues  (bug-tagged: $new_bugs)"
KV "open issues total" "$open_total"
KV "new PRs" "$new_prs"
KV "stars" "$stars"

H "Repo traffic (GitHub API — pushes need admin token)"
views_json=$(gh api "repos/$REPO/traffic/views" 2>/dev/null || echo '{}')
views_total=$(echo "$views_json" | jq -r '.count // "?"')
views_unique=$(echo "$views_json" | jq -r '.uniques // "?"')
clones_json=$(gh api "repos/$REPO/traffic/clones" 2>/dev/null || echo '{}')
clones_total=$(echo "$clones_json" | jq -r '.count // "?"')
KV "page views (14d)" "$views_total  (unique: $views_unique)"
KV "git clones (14d)" "$clones_total"

H "Recent issue comments (signals)"
gh issue list --repo "$REPO" --state all --search "updated:>=$since_iso" --json number,title,updatedAt,labels --jq '.[] | "  #\(.number)  \(.title)  [\(.labels | map(.name) | join(","))]  \(.updatedAt)"' 2>/dev/null | head -10 || echo "  (none)"

if [[ "$MARKDOWN" -eq 1 ]]; then
  echo ""
  echo "---"
  echo "_Generated by \`scripts/release-monitor.sh\` on $(date -u +%FT%TZ)_"
fi
